### ISSUE TITLE
Landing: href Links

### ISSUE THREAD

**Issue by maxCardo** [maxCardo/mcidx#11]
Add href endpoints to nav bar for 

Search: http://cardo.idxbroker.com/idx/search/
Map Search: http://cardo.idxbroker.com/idx/map/mapsearch

Home Valuation: Contact form
Rental Rate Projection: Contact Form

**Comment by dejn9** [comment]
I don't know what kind of comments I have to put here, but it's done

**Comment by maxCardo** [comment]
Good stuff

________________________________
