### ISSUE TITLE
IDX Mobile Menu Results

### ISSUE THREAD

**Issue by maxCardo** [maxCardo/mcidx#9]
Can we make the menu on this page collapse and be accessed via hamburger bar like the other pages

http://cardo.idxbroker.com/idx/results/listings?pt=sfr&lp=0&hp=800000

vs

 http://cardo.idxbroker.com/idx/details/listing/d504/1433303/214-Dilworth-Road-Sewickley-PA-15143

**Comment by BozidarSiljanoski** [comment]
we should keep this for later, I am not sure because that Refinement Search is very nasty

**Comment by BozidarSiljanoski** [comment]
Done
